/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanbing_mytest_module_TestJni_OnResultListener */

#ifndef _Included_com_hanbing_mytest_module_TestJni_OnResultListener
#define _Included_com_hanbing_mytest_module_TestJni_OnResultListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
