/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanbing_mytest_module_TestJni */

#ifndef _Included_com_hanbing_mytest_module_TestJni
#define _Included_com_hanbing_mytest_module_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanbing_mytest_module_TestJni
 * Method:    print
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hanbing_mytest_module_TestJni_print
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hanbing_mytest_module_TestJni
 * Method:    doInBackground
 * Signature: (Lcom/xhb/mytest/module/TestJni/OnResultListener;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hanbing_mytest_module_TestJni_doInBackground
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
